README.md

docs: update readme banner

---

src/agent.py

use dedicated headers to rank MCPMark on the OpenRouter
refs: https://openrouter.ai/docs/quickstart#using-the-openai-sdk

chore: use dedicated headers

---

docs/introduction.md

Latex syntax will case website build fail

docs: fix introduction

---

pipeline.py
src/aggregators/aggregate_results.py
src/evaluator.py

feat: reconstruct log file structure

---

pipeline.py
src/aggregators/aggregate_results.py
src/evaluator.py
src/model_config.py
src/results_reporter.py

fix: handle null reasoning token

---

pyproject.toml
requirements.txt

feat: add litellm dependency

---

src/agents/mcpmark_agent.py

feat: improve notion tool calling in gemini

---

src/agents/mcpmark_agent.py

feat: improve output tokens calculation

---

docs/introduction.md

📝 docs: fix introduction.md

---

src/agents/mcpmark_agent.py

feat: improve litellm error handling

---

src/agents/mcpmark_agent.py
src/errors.py
src/evaluator.py

🐛 fix: handle timeout error, add timeout error for resuming

---

src/aggregators/aggregate_results.py

…k-expeirments only)
`--push` and `--branch` is for `mcpmark-experiments` repo use only.

✨ feat: comprehensive aggregator, enbale push to new branch

---

src/aggregators/aggregate_results.py
src/aggregators/pricing.py
src/model_config.py

🔨 chore: update price info

---

src/agents/mcpmark_agent.py

🐛 fix: improve claude error handling

---

src/mcp_services/notion/notion_state_manager.py

- cache eval/source hub page IDs to avoid repeated cross-workspace searches
- reuse cached IDs when locating templates and fallback duplicates via block children listings
- clean up orphan duplicates with child listing instead of global search

✨ feat: refine Notion parent resolution and duplicate recovery

---

tasks/github/missing-semester/find_legacy_name/verify.py
tasks/notion/company_in_a_box/goals_restructure/verify.py

We should skip checking the child block existence for newly added goal, as the task doesn't ask to add new description for the new goal. And the task is unclear that if a new empty child block should be added or not. We should either change the the task prompt or verification.
[Task](https://mcpmark.ai/tasks/goals_restructure)

Fix verification in Notion task company_in_a_box/goals_restructure

---

CHANGELOG.md

📝 docs: release v1.2.0

---

CHANGELOG.md

📝 docs: Update CHANGELOG.md

---

docs/datasets/task.md
src/errors.py

fix typo in docs
this fix #203

🔨 chore: fix typo

---

pyproject.toml

🐛 fix: fix openai package dependency

---

src/agents/mcpmark_agent.py

Added structured logging of available tools to `execution.log`. No impact on existing functionality.
When running this project, I want to know the optional tools for each task—this allows me to observe the AI's specific tool selection at a more granular level. Directing the list of available tools to `execution.log` is the approach I currently think of that minimizes disruption to the project structure.

✨ feat: add ToolLog to execution.log
